name: push to docker hub

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKERH UB_URL }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: "${{ secrets.DOCKERHUB_URL }}/${{ secrets.DOCKERHUB_USERNAME }}/rb-global-client:latest"
          cache-from: "type=registry,ref=${{ secrets.DOCKERHUB_URL }}/rb-global-client:buildcache"
          cache-to: "type=registry,ref=${{ secrets.DOCKERHUB_URL }}/rb-global-client:buildcache,mode=max"
